sudo: required

language: generic

services: 
    - docker

before_install:
    - docker build -t sergerodriguezequisoft/react-test -f ./client/Dockerfile.dev ./client

script:
  - docker run -e CI=true sergerodriguezequisoft/react-test npm test

after_success:
    - docker build -t sergerodriguezequisoft/multi-client ./client  
    - docker build -t sergerodriguezequisoft/multi-nginx ./nginx  
    - docker build -t sergerodriguezequisoft/multi-server ./server  
    - docker build -t sergerodriguezequisoft/multi-worker ./worker
    
    # Log in to the Docker CLI
    - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_ID" --password-stdin docker.io

    # Take those images and push them to Docker Hub
    - docker push sergerodriguezequisoft/multi-client   
    - docker push sergerodriguezequisoft/multi-nginx  
    - docker push sergerodriguezequisoft/multi-server  
    - docker push sergerodriguezequisoft/multi-worker  

deploy:
    provider: elasticbeanstalk
    region: "us-east-2"
    app: "multi-docker"
    env: "MultiDocker-env"
    bucket_name: "elasticbeanstalk-us-east-2-069858209185"
    bucket_path: "docker-multi"
    on:
        branch: master
    access_key_id: $AWS_ACCESS_KEY
    secret_access_key: $AWS_SECRET_KEY